accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('success/', views.SignUpSuccessView.as_view(), name='success'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('password/',views.password, name='password' ),
    path('accounts/profile/',views.log_success, name='log_success')
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path("", views.index, name='index'),
]

comment/urls.py
from . import views
from django.urls import path

app_name = 'comment'

urlpatterns = [
    path('commentbase/',views.commentbase,name="commentbase"),
    path('comment/',views.comment,name='comment'),
    path('comment/',views.CommentView.as_view(),name='comment'),
    path('success/',views.success,name='success'),
]

post/urls.py
from .import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = "post"

urlpatterns = [
    path('post/',views.post,name="post"),
    path('comp/', views.comp,name="comp"),
    path('view/', views.view2,name="view"),
    path('view/<int:post_id>',views.syousai,name="syousai"),
]
if settings.DEBUG:
    urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('accounts.urls')),
    path('', include('post.urls')),
    path('', include('comment.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

app/models.py
from django.db import models

# Create your models here.

comment/models.py
from django.db import models
from django.utils import timezone

class Commentmodels(models.Model):
    users = models.CharField(verbose_name='ユーザ名',max_length=100)
    comment = models.CharField(verbose_name='内容',max_length=500)
    publishe_date = models.DateTimeField(verbose_name='投稿日時',blank=True, null=True)

    def publish(self):
        self.publishe_date = timezone.now()
        self.save()

post/models.py
from django.db import models
from django.utils import timezone

class Postmodels(models.Model):
    title = models.CharField(verbose_name='タイトル',max_length=100)
    media = models.ImageField(verbose_name='画像',upload_to='photo',blank=True, null=True)
    post = models.CharField(verbose_name='内容',max_length=1000)
    published_date = models.DateTimeField(verbose_name='投稿日時',blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()


class Commentmodels(models.Model):
    users = models.CharField(default='名無し',max_length=100)
    comment = models.CharField(verbose_name='内容',max_length=500)
    publishe_date = models.DateTimeField(verbose_name='投稿日時',blank=True, null=True)

    def publish(self):
        self.publishe_date = timezone.now()
        self.save()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

comment/forms.py
from django import forms
from .models import Commentmodels

class CommentForm(forms.ModelForm):
    class Meta:
        model = Commentmodels
        fields = ('users','comment')

post/forms.py
from django import forms
from .models import Postmodels

class PostForm(forms.ModelForm):
    class Meta:
        model = Postmodels
        fields = ['title','media','post']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth import login
from .models import CustomUser
from django.http import HttpResponse,HttpResponseRedirect

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('accounts:success')

    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)


class SignUpSuccessView(TemplateView):
    template_name = 'success.html'

def password(request):
    return render(request,'password.html')

def log_success(request):
    return render(request,'log_success.html')

app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

comment/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.template import loader
from .models import Commentmodels
from .forms import CommentForm
from django.http import HttpResponse
from django.utils import timezone
from django.views.generic import CreateView,DeleteView

def commentbase(request):
    comment = Commentmodels.objects.all()
    context = {'comment':comment}
    template = loader.get_template('commentbase.html')
    return HttpResponse(template.render(context,request))

def comment(request):
    if request.method == "POST":
        forms = CommentForm(request.POST)
        if forms.is_valid():
            comment = Commentmodels()
            print(request)
            comment.users = request.POST['users']
            comment.comment = request.POST['comment']
            comment.publishe_date = timezone.now()
            comment.save()
            return redirect('/success', pk=comment.pk)
    else:
        forms = CommentForm()
    return render(request, 'comment.html', {'forms': forms})

def success(request):
    return render(request,'success.html')

class CommentView(CreateView):
    model = Commentmodels
    form_class = CommentForm
    def form_valid(self, form):
        form.instence.author = self.request.user
        # article_pk = self.kwargs.get('pk')
        comment = form.save(commit=False)
        comment.save()
        return redirect('comment:success')
    

post/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from .forms import PostForm
from .models import Postmodels
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin





def post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = Postmodels()
            print(request)
            post.title = request.POST['title']
            post.post = request.POST['post']
            post.media = request.FILES['media']
            post.published_date = timezone.now()
            post.save()
            return redirect('/comp', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'post.html', {'form': form})

def comp(request):
    return render(request,'comp.html')

def view(request):
    title = request.POST.get('title')
    post = Postmodels(title=title)
    post.save()
    return HttpResponseRedirect(reverse('post:view2'))

def view2(request):
    post = Postmodels.objects.all()
    context = {'post':post}
    template = loader.get_template('view.html')
    return HttpResponse(template.render(context,request))


def syousai(request, post_id):
    post = Postmodels.objects.get(id=post_id)
    context = {'post':post}
    template = loader.get_template('syousai.html')
    return HttpResponse(template.render(context,request))



    

accounts/templates/log_success.html
<h2>ログインしました</h2>
<a href="{% url 'app:index' %}">topに戻る</a>

accounts/templates/login.html
{% extends 'base.html' %}
    
{% block title %}
<title>login</title>
<main class="form-signin w-100 m-auto">
    {%if form.errors %}
    <p style="color: red">ユーザ名とパスワードが一致しません</p>
    {% endif %}
  <form method="post">
    {% csrf_token %}
    <label for="Username" class="visually-hidden">ユーザー名</label>
    <input type="text"
          name="username"
          id="id_username"
          maxlength="150"
          autocapitalize="none"
          autocomplete="username"
          class="form-control"
          placeholder="ユーザ名を入力"
          required
          autofocus>
        <br>    
      <label for="Password" class="visually-hidden">パスワード</label>
      <input type="password"
            name="password"
            id="id_password"
            autocomplete="current-password"
            class="form-control"
            placeholder="パスワードを入力"
            required
            autofocus>
      <br>
    <!-- <label for="submit" class="visually-hidden"></label> -->
      <input class="w-20 btn btn-lg btn-primary"
              type="submit"
              value="ログイン" />
    <br>
      <a href="{% url 'accounts:password' %}">パスワードを忘れましたか？</a>
    </form>
  </main>
{% endblock %}

accounts/templates/logout.html
<div class="container">
    <div class="row">
        <div class="col offset-4 py-4">
            <h3>ログアウトしました</h3>
            <p><a href="{% url 'app:index' %}">トップページ</a></p>
        </div>
    </div>
</div>

accounts/templates/password.html
<section>
<div class="center-item">
<h1>どんまい^^</h1>
</div>
</section>

accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up {% endblock %}

    {% block contents %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method = "post">
                    {% csrf_token %}
                    {% for field in form %}
                    <p>
                        {{ field.label_tag }}<br>
                        {{ field }}

                        
                        {% for error in field.error %}
                            <p style="color:red">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    <p style="color:red">
                    ※メールアドレスはパスワードをリセットする際に必要になりますので、ご登録お願いします
                    </p>
                    <input type="submit" value="Sign up">
                </form>
                <br>
                <p><a href="{% url 'app:index'%}">登録をやめてトップページに戻る</a></p>
                
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/success.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<div class="contraner">
    <div class="row">
        <div class="col affet-4 py-4">
            <h3>登録が完了しました。</h3>
            <p><a href="{% url 'accounts:login'%}">ログインはこちら</a></p>
        </div>
    </div>
</div>
{% endblock %}

app/templates/base.html
{% load static%}
<!--メニュー-->
<nav id="menubar">
<ul>
	{% if user.is_authenticated %}
<div>
    <h3>{{ user }}でログイン中</h3>
</div>
{% else %}
{% endif %}
    {% if user.is_authenticated %}
    <li><a href="{% url 'post:post' %}">投稿</a></li>
    <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
    {% else %}
    <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
    <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
    {% endif %}
    <li><a href="{% url 'post:view' %}">閲覧</a></li>
    <li><a href="{% url 'comment:commentbase' %}">評価</a></li>

<!--タイトル-->
{% block title %}
{% endblock %}

<!--本文-->
{% block contents %}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block contents %}
{% endblock %}

comment/templates/comment.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<h2>コメント</h2>
{% endblock %}

{% block contents %}
    {% csrf_token %}
           
<form method="POST" class="comment-form" enctype="multipart/form-data" id="comment-form">
    {% csrf_token %}
    {{ forms.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
    <p><a href="{% url 'post:view' %}">戻る</a></p>

{% endblock %}

comment/templates/commentbase.html
{% extends 'base.html' %}

{% block title %}
<h2>このサイトの評価</h2>
{% endblock %}

{% block contents %}
<a href="{% url 'comment:comment' %}">コメントする</a>

<hr>

{% for comment in comment %}
{% csrf_token %}
    {{ comment.users }}:{{ comment.publishe_date }}<br>
    {{ comment.comment }}<br>
<hr>
{% endfor %}

{% endblock %}

comment/templates/success.html
{% extends 'base.html' %}

{% block contents %}
コメントしました！
<a href="{% url 'comment:commentbase' %}">戻る</a>
{% endblock %}

post/templates/comment.html
{% extends 'base.html' %}

{% block title %}
<h2>コメント</h2>
{% endblock %}

{% block contents %}
    {% csrf_token %}
           
<form method="POST" class="comment-form" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    {{ forms.users }}
    {{ forms.comment }}
    <button type="submit" class="save btn btn-default">Save</button>

    </form> 
    </div>
    <p><a href="{% url 'post:view' %}">戻る</a></p>

{% endblock %}

post/templates/comp.html
{% extends 'base.html' %}

{% block title %}
{% csrf_token %}
<h2>投稿しました！</h2>
<a href="{% url 'post:view' %}">閲覧する</a>
<a href="{% url 'app:index' %}">トップに戻る</a>
{% endblock %}

post/templates/post.html
{% extends 'base.html' %}

{% block title %}
<h2>投稿</h2>
{% endblock %}

{% block  contents%}
{% for post in post %}
        <div class="post">
        {% if post.image %}
        <div class ="media">
            <img src="{{ post.media.url }}" style="width:300px;height:auto">
        </div>
        {% endif %}
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.link|linebreaksbr }}</p>
        </div>
{% endfor %}
<form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
<!-- </form>
    <br>
    <h1>投稿・更新ページ</h1>
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">保存</button>
    </form>
    <br><br> -->
{% endblock %}

post/templates/syousai.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}


{% block contents %}

{% csrf_token %}
<div>
    <p>
    {{ post.title }}<br>
    内容:{{ post.post }}<br>
    <img src="../photo/{{post.media}}" width="200" height="150"><br>
    日付:{{ post.published_date }}<br>
    
</div>
<a href="{% url 'post:view' %}">戻る</a>
{% endblock %}

post/templates/view.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
<h2>一覧ページ</h2>
{% endblock %}


{% block contents %}
{% for post in post %}
<div>
    <li>
    <a href="{% url 'post:syousai' post_id=post.id%}">{{ post.title }}</a>
    </li>
</div>  
    
{% endfor %}
{% endblock %}